/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVoiceRouteImport } from './routes/dashboard.voice'
import { Route as DashboardTutorRouteImport } from './routes/dashboard.tutor'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardQuizRouteImport } from './routes/dashboard.quiz'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMaterialsRouteImport } from './routes/dashboard.materials'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiGenerateQuizRouteImport } from './routes/api/generate-quiz'
import { Route as ApiEmbedPdfRouteImport } from './routes/api/embed-pdf'
import { Route as ApiAskPdfRouteImport } from './routes/api/ask-pdf'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoiceRoute = DashboardVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTutorRoute = DashboardTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizRoute = DashboardQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaterialsRoute = DashboardMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateQuizRoute = ApiGenerateQuizRouteImport.update({
  id: '/api/generate-quiz',
  path: '/api/generate-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedPdfRoute = ApiEmbedPdfRouteImport.update({
  id: '/api/embed-pdf',
  path: '/api/embed-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskPdfRoute = ApiAskPdfRouteImport.update({
  id: '/api/ask-pdf',
  path: '/api/ask-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/api/ask-pdf': typeof ApiAskPdfRoute
  '/api/embed-pdf': typeof ApiEmbedPdfRoute
  '/api/generate-quiz': typeof ApiGenerateQuizRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tutor': typeof ApiTutorRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tutor': typeof DashboardTutorRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/api/ask-pdf': typeof ApiAskPdfRoute
  '/api/embed-pdf': typeof ApiEmbedPdfRoute
  '/api/generate-quiz': typeof ApiGenerateQuizRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tutor': typeof ApiTutorRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tutor': typeof DashboardTutorRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/api/ask-pdf': typeof ApiAskPdfRoute
  '/api/embed-pdf': typeof ApiEmbedPdfRoute
  '/api/generate-quiz': typeof ApiGenerateQuizRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tutor': typeof ApiTutorRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tutor': typeof DashboardTutorRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/reviews'
    | '/api/ask-pdf'
    | '/api/embed-pdf'
    | '/api/generate-quiz'
    | '/api/tts'
    | '/api/tutor'
    | '/dashboard/analytics'
    | '/dashboard/materials'
    | '/dashboard/profile'
    | '/dashboard/quiz'
    | '/dashboard/settings'
    | '/dashboard/tutor'
    | '/dashboard/voice'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/reviews'
    | '/api/ask-pdf'
    | '/api/embed-pdf'
    | '/api/generate-quiz'
    | '/api/tts'
    | '/api/tutor'
    | '/dashboard/analytics'
    | '/dashboard/materials'
    | '/dashboard/profile'
    | '/dashboard/quiz'
    | '/dashboard/settings'
    | '/dashboard/tutor'
    | '/dashboard/voice'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/reviews'
    | '/api/ask-pdf'
    | '/api/embed-pdf'
    | '/api/generate-quiz'
    | '/api/tts'
    | '/api/tutor'
    | '/dashboard/analytics'
    | '/dashboard/materials'
    | '/dashboard/profile'
    | '/dashboard/quiz'
    | '/dashboard/settings'
    | '/dashboard/tutor'
    | '/dashboard/voice'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  ApiAskPdfRoute: typeof ApiAskPdfRoute
  ApiEmbedPdfRoute: typeof ApiEmbedPdfRoute
  ApiGenerateQuizRoute: typeof ApiGenerateQuizRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiTutorRoute: typeof ApiTutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voice': {
      id: '/dashboard/voice'
      path: '/voice'
      fullPath: '/dashboard/voice'
      preLoaderRoute: typeof DashboardVoiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tutor': {
      id: '/dashboard/tutor'
      path: '/tutor'
      fullPath: '/dashboard/tutor'
      preLoaderRoute: typeof DashboardTutorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz': {
      id: '/dashboard/quiz'
      path: '/quiz'
      fullPath: '/dashboard/quiz'
      preLoaderRoute: typeof DashboardQuizRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/materials': {
      id: '/dashboard/materials'
      path: '/materials'
      fullPath: '/dashboard/materials'
      preLoaderRoute: typeof DashboardMaterialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-quiz': {
      id: '/api/generate-quiz'
      path: '/api/generate-quiz'
      fullPath: '/api/generate-quiz'
      preLoaderRoute: typeof ApiGenerateQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed-pdf': {
      id: '/api/embed-pdf'
      path: '/api/embed-pdf'
      fullPath: '/api/embed-pdf'
      preLoaderRoute: typeof ApiEmbedPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask-pdf': {
      id: '/api/ask-pdf'
      path: '/api/ask-pdf'
      fullPath: '/api/ask-pdf'
      preLoaderRoute: typeof ApiAskPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardMaterialsRoute: typeof DashboardMaterialsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQuizRoute: typeof DashboardQuizRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTutorRoute: typeof DashboardTutorRoute
  DashboardVoiceRoute: typeof DashboardVoiceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardMaterialsRoute: DashboardMaterialsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQuizRoute: DashboardQuizRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTutorRoute: DashboardTutorRoute,
  DashboardVoiceRoute: DashboardVoiceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  ApiAskPdfRoute: ApiAskPdfRoute,
  ApiEmbedPdfRoute: ApiEmbedPdfRoute,
  ApiGenerateQuizRoute: ApiGenerateQuizRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiTutorRoute: ApiTutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
